version: '3.8'

services:
  mysql:
    container_name: vollmed-db
    image: mysql
    environment:
      MYSQL_DATABASE: "vollmed_api"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    restart: unless-stopped

volumes:
  mysql-db: